#!/usr/bin/env python3
"""
Phase 1: Extract C/C++ functions from the OpenAirInterface5G codebase using tree-sitter.

Produces a JSONL file with one entry per function containing:
  - name, file (relative path), start_line, end_line
  - signature (return type + params)
  - subsystem tag derived from directory path
  - token_estimate (rough count based on whitespace-split)

Usage:
    python scripts/extract_functions.py \
        --repo-root openairinterface5g \
        --output data/oai5g_functions.jsonl

Requires (install inside project venv):
    pip install tree-sitter tree-sitter-c tree-sitter-cpp
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

try:
    from tree_sitter import Language, Parser
    import tree_sitter_c as tsc
    import tree_sitter_cpp as tscpp
except ImportError:
    sys.exit(
        "Missing dependencies. Install them in your project venv:\n"
        "  pip install tree-sitter tree-sitter-c tree-sitter-cpp"
    )

# ---------------------------------------------------------------------------
# Directories to scan inside the OAI5G repo
# ---------------------------------------------------------------------------
SCAN_DIRS = [
    "openair1",
    "openair2",
    "openair3",
    "common",
    "executables",
    "radio",
    "nfapi",
]

# Extensions to consider
C_EXTENSIONS = {".c", ".h"}
CPP_EXTENSIONS = {".cpp", ".cc", ".cxx", ".hpp", ".hxx"}
ALL_EXTENSIONS = C_EXTENSIONS | CPP_EXTENSIONS

# Minimum function body line count (inclusive) to keep
MIN_BODY_LINES = 5

# Markers that suggest auto-generated code
GENERATED_MARKERS = [
    "generated by",
    "auto-generated",
    "do not edit",
    "do not modify",
    "automatically generated",
    "machine generated",
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _derive_subsystem(rel_path: str) -> str:
    """Derive a coarse subsystem tag from the relative file path.

    Examples:
        openair1/PHY/foo.c          -> openair1/PHY
        openair2/LAYER2/MAC/bar.c   -> openair2/LAYER2/MAC
        common/utils/x.c            -> common/utils
    """
    parts = Path(rel_path).parts
    # Take up to 3 directory components (skip the filename)
    dir_parts = parts[:-1]  # drop filename
    depth = min(len(dir_parts), 3)
    return "/".join(dir_parts[:depth]) if dir_parts else "root"


def _estimate_tokens(text: str) -> int:
    """Rough token estimate by splitting on whitespace + punctuation."""
    # A simple heuristic: split on whitespace, count. Roughly 1.3x actual
    # BPE tokens for C code, but good enough for filtering.
    return len(text.split())


def _is_generated(source_bytes: bytes, start_byte: int) -> bool:
    """Check if the file region near the function contains generation markers."""
    # Look at the first 2048 bytes of the file for markers
    header = source_bytes[:2048].decode("utf-8", errors="replace").lower()
    return any(marker in header for marker in GENERATED_MARKERS)


def _is_static_inline_header(node, file_ext: str) -> bool:
    """Detect static inline functions in header files."""
    if file_ext not in (".h", ".hpp", ".hxx"):
        return False
    # Walk storage class specifiers
    for child in node.children:
        if child.type == "storage_class_specifier" and child.text:
            text = child.text.decode("utf-8", errors="replace")
            if text == "static":
                # Check for inline
                for sibling in node.children:
                    if sibling.type == "type_qualifier" and sibling.text:
                        qual = sibling.text.decode("utf-8", errors="replace")
                        if qual == "inline":
                            return True
                    # Also handle __inline, __attribute__((always_inline)) loosely
                    if sibling.type == "storage_class_specifier" and sibling.text:
                        spec = sibling.text.decode("utf-8", errors="replace")
                        if "inline" in spec.lower():
                            return True
    return False


def _extract_signature(node, source_bytes: bytes) -> str:
    """Extract a compact function signature from the AST node.

    Returns something like: 'int foo(int a, const char *b)'
    """
    # The full text up to the compound_statement (body) is the signature
    body_start = None
    for child in node.children:
        if child.type == "compound_statement":
            body_start = child.start_byte
            break
    if body_start is not None:
        sig_bytes = source_bytes[node.start_byte:body_start]
    else:
        # Fallback: use first line
        sig_bytes = source_bytes[node.start_byte:node.end_byte]

    sig = sig_bytes.decode("utf-8", errors="replace").strip()
    # Collapse whitespace
    sig = " ".join(sig.split())
    # Truncate if very long
    if len(sig) > 512:
        sig = sig[:509] + "..."
    return sig


def _extract_name(node) -> str | None:
    """Extract function name from a function_definition node."""
    # Look for declarator -> direct children named 'identifier' or
    # 'function_declarator' -> 'identifier'
    def _find_name(n):
        if n.type == "identifier":
            return n.text.decode("utf-8", errors="replace")
        if n.type in ("function_declarator", "declarator",
                       "pointer_declarator", "parenthesized_declarator"):
            for child in n.children:
                result = _find_name(child)
                if result:
                    return result
        return None

    for child in node.children:
        if child.type in ("declarator", "function_declarator",
                          "pointer_declarator"):
            name = _find_name(child)
            if name:
                return name
    return None


# ---------------------------------------------------------------------------
# Main extraction
# ---------------------------------------------------------------------------

def extract_functions_from_file(
    file_path: Path,
    repo_root: Path,
    parser_c: Parser,
    parser_cpp: Parser,
) -> list[dict[str, Any]]:
    """Parse a single C/C++ file and return function metadata dicts."""

    ext = file_path.suffix.lower()
    if ext in C_EXTENSIONS:
        parser = parser_c
    elif ext in CPP_EXTENSIONS:
        parser = parser_cpp
    else:
        return []

    try:
        source_bytes = file_path.read_bytes()
    except (OSError, IOError):
        return []

    # Skip files with generation markers
    if _is_generated(source_bytes, 0):
        return []

    tree = parser.parse(source_bytes)
    rel_path = str(file_path.relative_to(repo_root))
    subsystem = _derive_subsystem(rel_path)
    results: list[dict[str, Any]] = []

    def _visit(node):
        if node.type == "function_definition":
            start_line = node.start_point[0] + 1  # 1-indexed
            end_line = node.end_point[0] + 1
            body_lines = end_line - start_line + 1

            # Filter: too short
            if body_lines < MIN_BODY_LINES:
                return

            # Filter: static inline in headers
            if _is_static_inline_header(node, ext):
                return

            name = _extract_name(node)
            if not name:
                return

            # Filter: test functions heuristic
            if "/tests/" in rel_path or "/test/" in rel_path or "/unittest/" in rel_path:
                return

            signature = _extract_signature(node, source_bytes)
            body_text = source_bytes[node.start_byte:node.end_byte].decode(
                "utf-8", errors="replace"
            )
            token_est = _estimate_tokens(body_text)

            results.append({
                "name": name,
                "file": rel_path,
                "start_line": start_line,
                "end_line": end_line,
                "body_lines": body_lines,
                "signature": signature,
                "subsystem": subsystem,
                "token_estimate": token_est,
            })
        else:
            for child in node.children:
                _visit(child)

    _visit(tree.root_node)
    return results


def collect_source_files(repo_root: Path) -> list[Path]:
    """Walk SCAN_DIRS and collect all C/C++ source files."""
    files: list[Path] = []
    for scan_dir in SCAN_DIRS:
        dir_path = repo_root / scan_dir
        if not dir_path.is_dir():
            print(f"  [skip] {scan_dir}/ not found", file=sys.stderr)
            continue
        for root, _dirs, filenames in os.walk(dir_path):
            for fname in filenames:
                fpath = Path(root) / fname
                if fpath.suffix.lower() in ALL_EXTENSIONS:
                    files.append(fpath)
    return files


def main():
    parser = argparse.ArgumentParser(
        description="Extract C/C++ functions from OAI5G for SERA/SVG data generation"
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path("openairinterface5g"),
        help="Path to OAI5G repo root (default: openairinterface5g)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("data/oai5g_functions.jsonl"),
        help="Output JSONL file path (default: data/oai5g_functions.jsonl)",
    )
    parser.add_argument(
        "--min-lines",
        type=int,
        default=MIN_BODY_LINES,
        help=f"Minimum function body lines to include (default: {MIN_BODY_LINES})",
    )
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    if not repo_root.is_dir():
        sys.exit(f"Repository root not found: {repo_root}")

    # Build parsers
    print("Initializing tree-sitter parsers...", file=sys.stderr)
    c_lang = Language(tsc.language())
    cpp_lang = Language(tscpp.language())

    parser_c = Parser(c_lang)
    parser_cpp = Parser(cpp_lang)

    # Collect files
    print(f"Scanning {repo_root} for C/C++ source files...", file=sys.stderr)
    source_files = collect_source_files(repo_root)
    print(f"  Found {len(source_files)} source files", file=sys.stderr)

    # Extract functions
    all_functions: list[dict[str, Any]] = []
    errors = 0
    for i, fpath in enumerate(source_files):
        if (i + 1) % 500 == 0:
            print(
                f"  Processed {i + 1}/{len(source_files)} files, "
                f"{len(all_functions)} functions so far...",
                file=sys.stderr,
            )
        try:
            funcs = extract_functions_from_file(fpath, repo_root, parser_c, parser_cpp)
            all_functions.extend(funcs)
        except Exception as e:
            errors += 1
            if errors <= 10:
                print(f"  [error] {fpath}: {e}", file=sys.stderr)

    # Write output
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w") as f:
        for func in all_functions:
            f.write(json.dumps(func) + "\n")

    # Summary statistics
    subsystem_counts: dict[str, int] = {}
    for func in all_functions:
        sub = func["subsystem"]
        subsystem_counts[sub] = subsystem_counts.get(sub, 0) + 1

    print(f"\nExtraction complete:", file=sys.stderr)
    print(f"  Total functions: {len(all_functions)}", file=sys.stderr)
    print(f"  Files processed: {len(source_files)}", file=sys.stderr)
    print(f"  Parse errors: {errors}", file=sys.stderr)
    print(f"  Output: {args.output}", file=sys.stderr)
    print(f"\n  Subsystem breakdown:", file=sys.stderr)
    for sub, count in sorted(subsystem_counts.items(), key=lambda x: -x[1]):
        print(f"    {sub}: {count}", file=sys.stderr)


if __name__ == "__main__":
    main()
