#!/usr/bin/env python3
"""
Generic C/C++ function extractor for any repository.

Walks the entire repo (excluding tests, generated code, vendored deps) and
extracts functions using tree-sitter. Produces JSONL compatible with the
SERA generate_data.py pipeline.

Usage:
    python scripts/extract_functions_generic.py \
        --repo-root repos/zephyr \
        --output data/zephyr/functions.jsonl

    python scripts/extract_functions_generic.py \
        --repo-root repos/nuttx \
        --output data/nuttx/functions.jsonl \
        --exclude-dirs arch/sim arch/x86_64

Requires:
    pip install tree-sitter tree-sitter-c tree-sitter-cpp
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

try:
    from tree_sitter import Language, Parser
    import tree_sitter_c as tsc
    import tree_sitter_cpp as tscpp
except ImportError:
    sys.exit(
        "Missing dependencies. Install:\n"
        "  pip install tree-sitter tree-sitter-c tree-sitter-cpp"
    )

C_EXTENSIONS = {".c", ".h"}
CPP_EXTENSIONS = {".cpp", ".cc", ".cxx", ".hpp", ".hxx"}
ALL_EXTENSIONS = C_EXTENSIONS | CPP_EXTENSIONS

MIN_BODY_LINES = 5

GENERATED_MARKERS = [
    "generated by", "auto-generated", "do not edit",
    "do not modify", "automatically generated", "machine generated",
]

# Directories to skip globally
SKIP_DIRS = {
    ".git", ".github", "__pycache__", "node_modules", ".venv",
    "build", "cmake-build", "_build", "out",
}

# Patterns in paths that indicate test code
TEST_PATTERNS = [
    "/tests/", "/test/", "/unittest/", "/testing/",
    "/test_", "_test/", "/mock/", "/mocks/",
    "/samples/", "/examples/",
]


def _derive_subsystem(rel_path: str, depth: int = 3) -> str:
    parts = Path(rel_path).parts
    dir_parts = parts[:-1]
    d = min(len(dir_parts), depth)
    return "/".join(dir_parts[:d]) if dir_parts else "root"


def _estimate_tokens(text: str) -> int:
    return len(text.split())


def _is_generated(source_bytes: bytes) -> bool:
    header = source_bytes[:2048].decode("utf-8", errors="replace").lower()
    return any(marker in header for marker in GENERATED_MARKERS)


def _is_test_path(rel_path: str) -> bool:
    lower = rel_path.lower()
    return any(pat in lower for pat in TEST_PATTERNS)


def _is_static_inline_header(node, file_ext: str) -> bool:
    if file_ext not in (".h", ".hpp", ".hxx"):
        return False
    has_static = False
    has_inline = False
    for child in node.children:
        if child.type == "storage_class_specifier" and child.text:
            text = child.text.decode("utf-8", errors="replace").lower()
            if text == "static":
                has_static = True
            if "inline" in text:
                has_inline = True
        if child.type == "type_qualifier" and child.text:
            qual = child.text.decode("utf-8", errors="replace").lower()
            if "inline" in qual:
                has_inline = True
    return has_static and has_inline


def _extract_signature(node, source_bytes: bytes) -> str:
    body_start = None
    for child in node.children:
        if child.type == "compound_statement":
            body_start = child.start_byte
            break
    if body_start is not None:
        sig_bytes = source_bytes[node.start_byte:body_start]
    else:
        sig_bytes = source_bytes[node.start_byte:node.end_byte]
    sig = " ".join(sig_bytes.decode("utf-8", errors="replace").split())
    return sig[:512] + "..." if len(sig) > 512 else sig


def _extract_name(node) -> str | None:
    def _find(n):
        if n.type == "identifier":
            return n.text.decode("utf-8", errors="replace")
        if n.type in ("function_declarator", "declarator",
                       "pointer_declarator", "parenthesized_declarator"):
            for child in n.children:
                result = _find(child)
                if result:
                    return result
        return None
    for child in node.children:
        if child.type in ("declarator", "function_declarator", "pointer_declarator"):
            name = _find(child)
            if name:
                return name
    return None


def extract_functions_from_file(
    file_path: Path,
    repo_root: Path,
    parser_c: Parser,
    parser_cpp: Parser,
) -> list[dict[str, Any]]:
    ext = file_path.suffix.lower()
    parser = parser_c if ext in C_EXTENSIONS else parser_cpp if ext in CPP_EXTENSIONS else None
    if parser is None:
        return []

    try:
        source_bytes = file_path.read_bytes()
    except (OSError, IOError):
        return []

    if _is_generated(source_bytes):
        return []

    tree = parser.parse(source_bytes)
    rel_path = str(file_path.relative_to(repo_root))

    if _is_test_path(rel_path):
        return []

    subsystem = _derive_subsystem(rel_path)
    results: list[dict[str, Any]] = []

    def _visit(node):
        if node.type == "function_definition":
            start_line = node.start_point[0] + 1
            end_line = node.end_point[0] + 1
            body_lines = end_line - start_line + 1

            if body_lines < MIN_BODY_LINES:
                return
            if _is_static_inline_header(node, ext):
                return

            name = _extract_name(node)
            if not name:
                return

            signature = _extract_signature(node, source_bytes)
            body_text = source_bytes[node.start_byte:node.end_byte].decode("utf-8", errors="replace")
            token_est = _estimate_tokens(body_text)

            results.append({
                "name": name,
                "file": rel_path,
                "start_line": start_line,
                "end_line": end_line,
                "body_lines": body_lines,
                "signature": signature,
                "subsystem": subsystem,
                "token_estimate": token_est,
            })
        else:
            for child in node.children:
                _visit(child)

    _visit(tree.root_node)
    return results


def collect_source_files(repo_root: Path, exclude_dirs: list[str] | None = None) -> list[Path]:
    exclude_set = set(exclude_dirs or [])
    files: list[Path] = []
    for root, dirs, filenames in os.walk(repo_root):
        # Prune skip dirs
        rel_root = os.path.relpath(root, repo_root)
        dirs[:] = [
            d for d in dirs
            if d not in SKIP_DIRS
            and os.path.join(rel_root, d) not in exclude_set
            and not d.startswith(".")
        ]
        for fname in filenames:
            fpath = Path(root) / fname
            if fpath.suffix.lower() in ALL_EXTENSIONS:
                files.append(fpath)
    return files


def main():
    parser = argparse.ArgumentParser(
        description="Generic C/C++ function extractor for SERA pipeline"
    )
    parser.add_argument("--repo-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--min-lines", type=int, default=5)
    parser.add_argument("--exclude-dirs", nargs="*", default=[],
                        help="Relative dirs to exclude (e.g. 'arch/sim')")
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    if not repo_root.is_dir():
        sys.exit(f"Repo not found: {repo_root}")

    print(f"Initializing tree-sitter parsers...", file=sys.stderr)
    c_lang = Language(tsc.language())
    cpp_lang = Language(tscpp.language())
    parser_c = Parser(c_lang)
    parser_cpp = Parser(cpp_lang)

    print(f"Scanning {repo_root} for C/C++ source files...", file=sys.stderr)
    source_files = collect_source_files(repo_root, args.exclude_dirs)
    print(f"  Found {len(source_files)} source files", file=sys.stderr)

    all_functions: list[dict[str, Any]] = []
    errors = 0
    for i, fpath in enumerate(source_files):
        if (i + 1) % 1000 == 0:
            print(f"  Processed {i+1}/{len(source_files)}, {len(all_functions)} functions...", file=sys.stderr)
        try:
            funcs = extract_functions_from_file(fpath, repo_root, parser_c, parser_cpp)
            all_functions.extend(funcs)
        except Exception as e:
            errors += 1
            if errors <= 10:
                print(f"  [error] {fpath}: {e}", file=sys.stderr)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w") as f:
        for func in all_functions:
            f.write(json.dumps(func) + "\n")

    subsystem_counts: dict[str, int] = {}
    for func in all_functions:
        sub = func["subsystem"]
        subsystem_counts[sub] = subsystem_counts.get(sub, 0) + 1

    print(f"\nExtraction complete:", file=sys.stderr)
    print(f"  Total functions: {len(all_functions)}", file=sys.stderr)
    print(f"  Files processed: {len(source_files)}", file=sys.stderr)
    print(f"  Parse errors: {errors}", file=sys.stderr)
    print(f"  Output: {args.output}", file=sys.stderr)
    print(f"\n  Top 30 subsystems:", file=sys.stderr)
    for sub, count in sorted(subsystem_counts.items(), key=lambda x: -x[1])[:30]:
        print(f"    {sub}: {count}", file=sys.stderr)


if __name__ == "__main__":
    main()
